services:
  - type: web
    name: ams-backend
    env: docker
    region: ohio
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: JWT_SECRET
        value: 'RenderAMSSecureKeyHS512RenderAMSSecureKeyHS512RenderAMSSecureKeyHS512RenderAMSSecureKeyHS512'
      - key: PORT
        value: 8080
      - key: CLOUDMERSIVE_API_KEY
        sync: false
      - key: PDFBOLT_API_KEY
        sync: false
